# Set values and source this file.

export SSH_KEY_NAME=
export NEWHOST=
export NEWPASS=
export EMAIL=
export GIT_NAME=
export GIT_EMAIL=
export AUTO_REBOOT=

export INSTALL_OPENSMTPD=false
export ROOTMAIL=
export SMTPPASS=

export INSTALL_MONIT=false
export MONIT_MAILSERVER_ADDRESS=
export MONIT_MAILSERVER_PORT=
export MONIT_MAILSERVER_USERNAME=
export MONIT_MAILSERVER_PASSWORD=
export MONIT_ALERT_ADDRESSEE=
export MONIT_ALERT_SENDER=
